language: bash
sudo: required

addons:
    apt:
        sources:
            - debian-sid
        packages:
            - shellcheck

os:
    - linux
    - osx

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install screenresolution; fi

script:
    - time ./neofetch --ascii --config config/travis -v
    # See this wiki page for why we're disabling these errors.
    # https://github.com/dylanaraps/neofetch/wiki/Shellcheck-Exclusions
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then shellcheck neofetch -e SC1090,SC2009,SC2012,SC2016,SC2034,SC2128,SC2153,SC2154,SC2178,SC2010; fi
